# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Hobbyloop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1     # Tuist Fetch 1️⃣
    - uses: tuist/tuist-action@0.13.0
      with:
        command: 'fetch'
        arguments: ''
    - uses: tuist/tuist-action@0.13.0 # Tuist generate 2️⃣
      with:
        command: 'generate'
        arguments: ''
    - uses: tuist/tuist-action@0.13.0 # Tuist Build 📲
      with:
        command: 'build'
        arguments: ''
    - name: xcode build 🛠️
      run: |
        xcodebuild clean build -workspace "Hobbyloop.xcworkspace" -scheme "Hobbyloop" -destination "platform=iOS Simulator,name=iPhone 13 mini,OS=latest"
